[package]
name = "template_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = {version = "2.0", features=["full"]}
quote = "1.0"
regex = "1.11.1"
proc-macro2 = "1.0.89"

[lib]
proc-macro = true
